name: Docker image build and push
on: 
  push:
    branches:
      - master
  schedule:
    - cron:  '00 5 * * *'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      VERSION: main
      TAGVERSION: latest
      AVAILABLE: false
    strategy:
      matrix:
        VERSION: [main, last_upstream]
      fail-fast: false
    steps:
    - uses: actions/checkout@v3
    - name: Get latest prometheus release
      run: |
        export PROMETHEUS_LATEST=$(curl -s "https://api.github.com/repos/prometheus/prometheus/releases" | grep -Po '"tag_name": "\K.*?(?=")'|head -1)
        echo "VERSION=$PROMETHEUS_LATEST" >> ${GITHUB_ENV}
        echo "TAGVERSION=$PROMETHEUS_LATEST" >> ${GITHUB_ENV}
        echo "AVAILABLE=true" >> ${GITHUB_ENV}
      shell: bash
      if: matrix.VERSION == 'last_upstream'
    
    - name: Login to Dockerhub Registry
      run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USER }}" --password-stdin
      if: success()
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2.1.0
    
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2.4.0
    
    - name: Run Buildx
      run: |
        docker buildx build \
          --platform linux/386,linux/amd64 \
          --build-arg VERSION=$VERSION \
          --push \
          --tag urfin78/prometheus:${TAGVERSION} \
          --file ./Dockerfile .

    - name: Logout from Dockerhub Registry
      run: docker logout
    
    - name: Login to GitHub Package Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u "${{ github.actor }}" --password-stdin

    - name: Tag the last upstream image
      run: |
        docker pull urfin78/prometheus:${TAGVERSION}
        docker tag urfin78/prometheus:${TAGVERSION} docker.pkg.github.com/urfin78/docker-prometheus/prometheus:${TAGVERSION}
      if: matrix.VERSION == 'last_upstream'

    - name: Push the last upstream image to GPR
      run: docker push docker.pkg.github.com/urfin78/docker-prometheus/prometheus:${TAGVERSION}
      if: matrix.VERSION == 'last_upstream'
    
    - name: Tag the latest image
      run: |
        docker pull urfin78/prometheus:latest
        docker tag urfin78/prometheus:latest docker.pkg.github.com/urfin78/docker-prometheus/prometheus:latest
      if: matrix.VERSION == 'main'

    - name: Push the latest image to GPR
      run: docker push docker.pkg.github.com/urfin78/docker-prometheus/prometheus:latest
      if: matrix.VERSION == 'main'

    - name: Logout from Dockerhub Registry
      run: docker logout
