name: Docker image build and push
on: 
  push:
    branches:
    - testing

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      VERSION: latest
      AVAILABLE: false
    strategy:
      matrix:
        ARCH: [amd64, i386, arm32v6]
        VERSION: [latest, last_upstream]
      fail-fast: false
    steps:
    - uses: actions/checkout@v2
    - name: Get latest prometheus release
      run: |
        export PROMETHEUS_LATEST=$(curl -s "https://api.github.com/repos/prometheus/prometheus/releases" | grep -Po '"tag_name": "\K.*?(?=")'|head -1)
        echo "::set-env name=VERSION::$PROMETHEUS_LATEST"
        echo "::set-env name=AVAILABLE::true"
      shell: bash
      if: matrix.VERSION == 'last_upstream'

    - name: Set up Docker Buildx
      id: buildx
      uses: crazy-max/ghaction-docker-buildx@v3
      with:
        buildx-version: latest
        qemu-version: latest
    - name: Run Buildx
      run: |
        docker buildx build \
          --platform linux/386,linux/amd64,linux/arm/v6 \
          --build-arg VERSION=$VERSION \
          --output "type=image,push=false" \
          --file ./Dockerfile.amd64 .